<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Date_commit</name>
   <tag></tag>
   <elementGuidId>9e1495b2-de9c-4c1a-a974-187e507d18c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#generate_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='generate_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Generate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f858820e-523a-4bce-9db3-589cb4b572ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0e91ac26-acd4-4093-841b-b0dabe14e515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commit</value>
      <webElementGuid>b1ee7095-63d2-4f49-b096-f61bcee219cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Generate</value>
      <webElementGuid>151621f9-fc14-4a34-8eda-3a29bc33b082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disable_with</name>
      <type>Main</type>
      <value>Generating...</value>
      <webElementGuid>4ed5ca49-fa4f-4bb0-9fe0-f8f13d663a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary display-inline-block vertical_align_bottom </value>
      <webElementGuid>81965327-f801-4603-b5f3-17518fd94f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>generate_btn</value>
      <webElementGuid>cadd7b0e-c03c-4950-a85e-57ff81928122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disable-with</name>
      <type>Main</type>
      <value>Generate</value>
      <webElementGuid>7637de31-8999-454e-9ebf-e962cc416e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generate_btn&quot;)</value>
      <webElementGuid>3cbaf6f7-001c-4eda-80be-89fff9ef7c5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='generate_btn']</value>
      <webElementGuid>39d12f0c-2081-41ef-a0e6-dfd3bc16fd54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-fluid']/form/input[2]</value>
      <webElementGuid>ae7eb1f8-e5b9-4831-bc8d-2b50aa5bfd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input[2]</value>
      <webElementGuid>908d3e99-1ab7-4dcb-96f0-7b3c12093658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'commit' and @id = 'generate_btn']</value>
      <webElementGuid>7b9131c6-6060-4158-b870-3eb44e7aacb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
