<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply filters</name>
   <tag></tag>
   <elementGuidId>68cd2317-d059-4b56-9d1e-608acc0519b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mui-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Apply filters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>06c2126b-1287-4fa6-9347-01b5eb0e535c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiLoadingButton-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButtonBase-root apply-filters-btn css-19j5or9</value>
      <webElementGuid>ca531247-45f7-4d80-a043-6a949226f085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8bc08d4e-6099-4ab6-8daa-bc4b55269116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>309da5d1-0f61-4a09-993e-0b84a463179d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-1</value>
      <webElementGuid>a1fbcb69-cd4b-474d-ba6a-ec9fed45e364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply filters</value>
      <webElementGuid>0220f7dc-5cf9-4943-b771-5b775c3cd1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-1&quot;)</value>
      <webElementGuid>28442fe6-5b7c-4b7a-abfb-327ee5a548d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mui-1']</value>
      <webElementGuid>021525de-a080-4c33-9cf1-e706a8c3c3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-fluid']/div[2]/div/div[3]/form/div/div/div/div[2]/div/button</value>
      <webElementGuid>f7f82e0d-abba-45c3-84d7-1db6a6418626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All groups'])[1]/following::button[1]</value>
      <webElementGuid>179a6f18-83a0-4ab5-a387-324d5809cd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Policy'])[1]/preceding::button[1]</value>
      <webElementGuid>df92d165-beb3-43ca-8f61-fafe6217ecbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply filters']/parent::*</value>
      <webElementGuid>d96493a4-00ef-4f3a-b52c-7e58513c2a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2c2309a5-5fc5-4096-a1cb-1d3a54c6f427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'mui-1' and (text() = 'Apply filters' or . = 'Apply filters')]</value>
      <webElementGuid>6fff129e-9449-40e9-ae23-f739a2f87d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
