<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show Archived Patients_commit</name>
   <tag></tag>
   <elementGuidId>4f635c3d-df8d-4c93-9c52-96bd1ec056b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#generate_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='generate_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Generate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c2347e5-18ea-477d-ace8-7cd7a36a4b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0348072d-61db-4062-bb84-50dd90dbb819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commit</value>
      <webElementGuid>981ab2d5-cfa9-4b98-9b71-702faab9757c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Generate</value>
      <webElementGuid>74fdf5f3-6710-4dfd-a415-dea78b6218b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary display-inline-block vertical_align_bottom </value>
      <webElementGuid>3865190b-cb90-465e-be07-b3f652b355f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>generate_btn</value>
      <webElementGuid>399a386e-1553-4fc7-b542-16af0362d3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disable-with</name>
      <type>Main</type>
      <value>Generate</value>
      <webElementGuid>063756e9-966e-4ca0-a1c4-6bd390b11e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generate_btn&quot;)</value>
      <webElementGuid>60f6e78d-10d3-456c-9254-9a9342b6a4fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='generate_btn']</value>
      <webElementGuid>1a137d4f-c353-4507-9977-0df0cf6d0a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-fluid']/form/input</value>
      <webElementGuid>03fdd8e0-1132-416b-b9c0-33c6b2499652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/input</value>
      <webElementGuid>dd2fddfa-e96c-4671-8d58-38337902f1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'commit' and @id = 'generate_btn']</value>
      <webElementGuid>e71623f0-a356-446e-b3d7-d5ca3b890c09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
