<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Archive</name>
   <tag></tag>
   <elementGuidId>a5be9e5f-ff28-47e3-81f2-3d0de504f4ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#archive_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='archive_link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Archive&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c388741-196e-4061-ac39-73a7f78aaed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>archive_link</value>
      <webElementGuid>b6d73f5b-3ba7-4010-b02c-b131ce7d137d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>2b4ae25c-5a95-48da-82d5-ad5678fe82ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#archive</value>
      <webElementGuid>7e544461-0265-40d6-a9ff-dcefc9ba316c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>d7262237-b096-413a-beb2-055ff17ff52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orange_hover</value>
      <webElementGuid>d1143604-8177-4abe-8b34-e949e4f3ea12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Archive
        </value>
      <webElementGuid>d5e1d190-ca31-43e6-85df-60ef68bb6235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;archive_link&quot;)</value>
      <webElementGuid>b24a02e1-f7ce-467f-a61e-0b389d313a9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='archive_link']</value>
      <webElementGuid>8dd3cba1-d89c-4eed-bef7-8c48ac2b871a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-fluid']/div[3]/div[2]/ul/li[8]/a</value>
      <webElementGuid>5ba4f22a-5e72-48e7-98fd-45a4f067a31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Archive')]</value>
      <webElementGuid>9951c5e5-6038-422e-a463-79c031825477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dressings'])[1]/following::a[8]</value>
      <webElementGuid>448fcaeb-e42f-4933-8f02-7dbb0ec7538c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='December1'])[2]/following::a[8]</value>
      <webElementGuid>2423eb42-42cc-43e1-9eca-c0e70d9b8128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messages'])[1]/preceding::a[1]</value>
      <webElementGuid>9b6fedcb-dc90-4645-9a1d-2d406ba7e347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message for:'])[1]/preceding::a[1]</value>
      <webElementGuid>c318cc39-5e2a-4141-a586-28b3268bdd01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Archive']/parent::*</value>
      <webElementGuid>45d7d889-8167-42b9-92d2-7e3affdf84de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[18]</value>
      <webElementGuid>7a076aaa-b75d-4e82-a3ca-36c1ac3ea4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[8]/a</value>
      <webElementGuid>ffc5a1d6-fb71-4273-aa98-c91a51a7ebcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'archive_link' and @href = '#' and (text() = '
            Archive
        ' or . = '
            Archive
        ')]</value>
      <webElementGuid>a09605e3-aeb8-48e7-a281-6b8610143fe9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
