<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Incompatibilities</name>
   <tag></tag>
   <elementGuidId>ca8de21e-bdea-47bb-b241-c9d9c259441d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a.orange_hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container-fluid']/div[3]/div[2]/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Incompatibilities&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3828bda-56fb-4d76-a838-3519b67214d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4fafbf1f-bcbb-413d-b147-483a2d2acd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#incompatibilities</value>
      <webElementGuid>a7fdfcfb-a309-4dab-ab62-55e2506b71da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c1b685a2-08eb-49e7-810a-e44a626c2b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orange_hover</value>
      <webElementGuid>ba5a513c-7ebb-44dd-b4ad-e0852fff7e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Incompatibilities</value>
      <webElementGuid>d5d3df71-9032-46d8-b138-83fa58516540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-fluid&quot;)/div[@class=&quot;two-column&quot;]/div[@class=&quot;fat-column-right&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[6]/a[@class=&quot;orange_hover&quot;]</value>
      <webElementGuid>459b7d58-8224-4055-9e9f-de13f6d67a37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-fluid']/div[3]/div[2]/ul/li[6]/a</value>
      <webElementGuid>8c45247b-9909-4bc9-81b2-3813f77c0bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Incompatibilities')])[2]</value>
      <webElementGuid>ad14f459-7793-4d0b-b24b-2c79f6052acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dressings'])[1]/following::a[6]</value>
      <webElementGuid>5f47dbad-6bdb-4a3d-9ce0-9e2ba6b19f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='December1'])[2]/following::a[6]</value>
      <webElementGuid>39054c55-38a0-467d-8eac-bb68c228e768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messages'])[1]/preceding::a[3]</value>
      <webElementGuid>d480f02d-09c0-495a-943b-e67e18462f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message for:'])[1]/preceding::a[3]</value>
      <webElementGuid>3276c500-eb35-4cf7-b4cd-6bf4a0245fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[16]</value>
      <webElementGuid>d26e2602-f4c3-4133-8b01-0a401a5eb3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[6]/a</value>
      <webElementGuid>3de4a40a-7c6e-4c6c-9dad-e11c58d67cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Incompatibilities' or . = 'Incompatibilities')]</value>
      <webElementGuid>dbd9061e-018b-4f10-8415-f479de0cb386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
