<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leave</name>
   <tag></tag>
   <elementGuidId>9c8281dd-17fe-41c2-9f49-c51f557cd8bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.orange_hover.leave_tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container-fluid']/div[3]/div[2]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Leave&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d53fd0c9-447e-4b42-8fa0-6f3ab1f9de02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0eaeafc0-67d1-4f0f-adeb-ab2d68f54f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#leave</value>
      <webElementGuid>84e94355-a7fb-4dad-a705-127685628d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>38d2387f-4cba-4dc8-9ee7-43d6beba7a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orange_hover leave_tab</value>
      <webElementGuid>9b2d407a-fd6d-4e95-8039-38f32a125de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave</value>
      <webElementGuid>fc4f6691-67ad-496a-8518-fb7bd153c5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-fluid&quot;)/div[@class=&quot;two-column&quot;]/div[@class=&quot;fat-column-right&quot;]/ul[@class=&quot;nav nav-tabs&quot;]/li[2]/a[@class=&quot;orange_hover leave_tab&quot;]</value>
      <webElementGuid>cb5cf70e-14ba-4d0c-af92-97ea5443d2f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-fluid']/div[3]/div[2]/ul/li[2]/a</value>
      <webElementGuid>599a7e74-e505-450d-a750-f9722c9fa221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Leave')])[2]</value>
      <webElementGuid>6f1a1be0-768c-4e6f-8924-4f879ee2181d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dressings'])[1]/following::a[2]</value>
      <webElementGuid>9e782835-cc0c-472d-b3e3-e9aa7e5e0d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='December1'])[2]/following::a[2]</value>
      <webElementGuid>724ad124-7d8d-49d0-ae55-448007f3c6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Messages'])[1]/preceding::a[7]</value>
      <webElementGuid>8754d68c-63af-415f-8891-d41090030327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message for:'])[1]/preceding::a[7]</value>
      <webElementGuid>f73c3a44-8a93-4b06-a0c7-027a3483584e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leave']/parent::*</value>
      <webElementGuid>8d56a803-9f25-4566-9c5c-753843b4600d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>e65224c2-213f-4f30-94e2-a7afb3aadc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>33aaa04d-290c-49ac-ba6f-d7e29e087239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Leave' or . = 'Leave')]</value>
      <webElementGuid>48060b36-68d4-45b4-8f41-0f55273b5345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
