<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply filters</name>
   <tag></tag>
   <elementGuidId>f429a795-12af-4640-8990-be4bc4e0fe3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mui-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Apply filters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b45cf7a-2acf-4e37-bdee-82365eb81d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiLoadingButton-root MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeMedium MuiButton-containedSizeMedium MuiButtonBase-root apply-filters-btn css-19j5or9</value>
      <webElementGuid>1f9b56ed-2dba-4adb-8c63-ba587f3ff354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5343fec7-f92c-4f76-8910-e063ec9cc6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f7921d69-6b98-424d-b801-de7c5fd36b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-5</value>
      <webElementGuid>b3abf37e-4e3f-4fca-8702-bacf6defe11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply filters</value>
      <webElementGuid>376c4f59-fd3c-4bf2-8837-77844d9c54f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-5&quot;)</value>
      <webElementGuid>31f90171-30a6-47ba-8800-055d2dccdfb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mui-5']</value>
      <webElementGuid>68afe574-7203-4ddb-ba4a-5d8d392ef41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-fluid']/div[2]/div/div[3]/form/div/div/div/div[5]/div/button</value>
      <webElementGuid>ec6eacdd-d620-4067-a272-16bcf81368d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All groups'])[1]/following::button[1]</value>
      <webElementGuid>09074237-af7d-4737-aba6-6a73cb6663ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End - Week Ending'])[2]/following::button[1]</value>
      <webElementGuid>0b1bb700-1952-469d-8bf8-66e5d5c074d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Policy'])[1]/preceding::button[1]</value>
      <webElementGuid>9b7346e6-480b-4d5b-9228-60500a8b60e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply filters']/parent::*</value>
      <webElementGuid>a2e6bf65-1c47-46ab-9e1e-7faa3fe43cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>620cee9f-3144-4d45-93af-396cd7ce726d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'mui-5' and (text() = 'Apply filters' or . = 'Apply filters')]</value>
      <webElementGuid>a51d22f0-54d9-4cf6-8cb2-56580b887bbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
