<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Date_commit</name>
   <tag></tag>
   <elementGuidId>be166a21-17e6-42e5-a8da-f6c599e3f72f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#core_report_submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='core_report_submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Generate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd6794a8-3266-4b55-82bb-4cb27063afb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>384f7153-7587-41ad-9298-7f670d855f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commit</value>
      <webElementGuid>011da1ca-b5c0-4cf9-8024-f1d1e3ec4470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Generate</value>
      <webElementGuid>625d34ed-d941-4fcf-beec-845b1e30deba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success vertical_align_bottom</value>
      <webElementGuid>a0f126a8-8daf-4e21-8df7-a02e7c019687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>core_report_submit</value>
      <webElementGuid>7bbe22e8-fa81-41e2-bc43-255e7a8ce525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disable-with</name>
      <type>Main</type>
      <value>Generate</value>
      <webElementGuid>2a91bf8a-9527-4fc5-b142-a2917b96bdf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;core_report_submit&quot;)</value>
      <webElementGuid>0c700e2e-fff5-4681-b2db-144e08700d71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='core_report_submit']</value>
      <webElementGuid>a914ae33-f582-465a-a9e1-013e584054ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='core_report']/input[2]</value>
      <webElementGuid>30047d72-f49a-44d7-b1fd-0323b3875944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input[2]</value>
      <webElementGuid>2903cc98-23ad-41d2-a701-1cb7cfd9d105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'commit' and @id = 'core_report_submit']</value>
      <webElementGuid>25dc58f4-90f8-403c-9e22-e2e74038f822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
